use super::Entry;

pub(super) const ENTRIES: &[Entry] = &[
    ("docs/release.md", "docs/release-blockers.md"),
    ("docs/release.md", "concrete Completion evidence"),
    ("docs/release.md", "traceable Evidence"),
    ("docs/release-blockers.md", "must include the public URL"),
    (
        "docs/release.md",
        "tested public `DropSquash.dmg` matching the release notes Artifact URL",
    ),
    ("docs/release.md", "outside the repository"),
    (
        "docs/release.md",
        "release notes `Git commit` field to exactly",
    ),
    ("docs/release.md", "match the current short or full `HEAD`"),
    ("docs/release.md", "manual QA `App build` field"),
    ("docs/release.md", "current `HEAD`"),
    ("docs/release.md", "do not upload media files"),
    ("docs/release.md", "do not enable telemetry by default"),
    ("docs/release.md", "release notes `SHA-256` field"),
    ("docs/release.md", "update `CHANGELOG.md`"),
    (
        "docs/release.md",
        "`apps/desktop/src-tauri/tauri.conf.json` version",
    ),
    ("docs/release.md", "lowercase SHA-256 hex"),
    ("docs/release.md", "`App artifact` recorded"),
    (
        "docs/release.md",
        "Benchmark sample set CSV path must also match",
    ),
    ("docs/release.md", "Homebrew tap PR URL"),
    ("docs/release.md", "same-machine release candidate baseline"),
    ("docs/release.md", "manual QA"),
    ("docs/release.md", "clean git worktree"),
    (
        "docs/release.md",
        "`--output` target must be named `SHA256SUMS`",
    ),
    ("docs/release.md", "refuses to overwrite"),
    ("docs/release.md", "non-empty `.p8` file"),
    ("docs/release.md", "private key data"),
    ("docs/release.md", "Tauri updater remains disabled"),
    ("docs/release.md", "updater public key"),
    ("docs/release.md", "never commit the updater private key"),
    ("docs/release.md", "Do not commit `latest.json`"),
    ("docs/release.md", "update manifest files"),
    ("docs/release.md", "password manager with a tested backup"),
    ("docs/release.md", "GitHub Secrets"),
    (
        "docs/release.md",
        "installed users cannot receive trusted updates",
    ),
    ("README.md", "macOS today"),
    ("README.md", "Windows and Linux support is planned"),
    ("README.md", "native encoder unavailable error"),
    (
        "Cargo.toml",
        "repository = \"https://github.com/mt4110/drop-squash\"",
    ),
    ("docs/product.md", "macOS today"),
    ("docs/product.md", "Windows and Linux support is planned"),
    ("docs/privacy.md", "dropsquash receipt <output.mp4>"),
    (
        "docs/benchmarking.md",
        "at least three private local samples",
    ),
    ("docs/benchmarking.md", "--release-set"),
    ("docs/benchmarking.md", "absolute `--output-dir`"),
    ("docs/benchmarking.md", "20%"),
    ("docs/manual-qa.md", "manual QA Markdown fields"),
    ("docs/manual-qa.md", "manual QA Release Candidate rows"),
    ("docs/manual-qa.md", "productization status gate"),
    (
        "docs/manual-qa.md",
        "nix develop --command pnpm --dir apps/desktop install --frozen-lockfile",
    ),
    (
        "docs/manual-qa.md",
        "nix develop --command pnpm --dir apps/desktop/web install --frozen-lockfile",
    ),
    (
        "docs/manual-qa.md",
        "nix develop --command pnpm --dir apps/desktop tauri build --bundles app,dmg --no-sign --ci",
    ),
    (
        "docs/manual-qa.md",
        "Manual QA does not replace the required release notes URL fields",
    ),
    ("docs/manual-qa.md", "clean git worktree"),
    ("docs/manual-qa.md", "CSV path outside repo"),
    ("docs/manual-qa.md", "private store IDs"),
    (
        "docs/manual-qa.md",
        "pasted into the macOS Packaged App field table",
    ),
    ("website/README.md", "docs/release-blockers.md"),
    ("apps/desktop/src-tauri/tauri.conf.json", "!\"updater\""),
];
