use super::Entry;

pub(super) const ENTRIES: &[Entry] = &[
    ("docs/release.md", "docs/release-blockers.md"),
    ("docs/release.md", "concrete Completion evidence"),
    ("docs/release.md", "traceable Evidence"),
    ("docs/release-blockers.md", "must include the public URL"),
    ("docs/productization.md", "docs/release-blockers.md"),
    ("docs/productization.md", "final publish gate"),
    (
        "docs/productization.md",
        "refund/support contact copy gates",
    ),
    (
        "docs/productization.md",
        "conversion/queue/Trash/license action-state release notes evidence",
    ),
    (
        "docs/productization.md",
        "same-DMG manual QA signing evidence",
    ),
    ("docs/productization.md", "Gatekeeper no-warning evidence"),
    (
        "docs/productization.md",
        "release-notes URL reference matching",
    ),
    ("docs/release.md", "tested public `DropSquash.dmg`"),
    ("docs/release.md", "outside the repository"),
    (
        "docs/release.md",
        "release notes `Git commit` field to match",
    ),
    ("docs/release.md", "manual QA `App build` field"),
    ("docs/release.md", "current `HEAD`"),
    ("docs/release.md", "release notes `SHA-256` field"),
    ("docs/release.md", "`App artifact` recorded"),
    ("docs/release.md", "manual QA"),
    ("docs/release.md", "release-notes-prepare"),
    (
        "docs/release.md",
        "--markdown-output /tmp/dropsquash-release-notes-prepared.md",
    ),
    ("docs/release.md", "refuses to overwrite"),
    ("docs/release.md", "intentionally marked pending"),
    (
        "docs/release.md",
        "`release-notes-prepare` rejects artifacts older",
    ),
    ("docs/release.md", "than `HEAD`"),
    ("docs/release.md", "non-empty `.p8` file"),
    ("docs/release.md", "private key data"),
    ("README.md", "macOS today"),
    ("README.md", "Windows and Linux support is planned"),
    (
        "Cargo.toml",
        "repository = \"https://github.com/mt4110/drop-squash\"",
    ),
    ("docs/product.md", "macOS today"),
    ("docs/product.md", "Windows and Linux support is planned"),
    ("docs/privacy.md", "dropsquash receipt <output.mp4>"),
    (
        "docs/benchmarking.md",
        "at least three private local samples",
    ),
    ("docs/benchmarking.md", "--release-set"),
    ("docs/benchmarking.md", "absolute `--output-dir`"),
    ("docs/benchmarking.md", "20%"),
    (
        "docs/release-notes-template.md",
        "CSV path outside the repository",
    ),
    (
        "docs/reproducible-builds.md",
        "nix develop --command pnpm --dir apps/desktop tauri build --bundles app,dmg --no-sign --ci",
    ),
    ("docs/manual-qa.md", "manual QA Markdown fields"),
    ("docs/manual-qa.md", "manual QA Release Candidate rows"),
    ("docs/manual-qa.md", "CSV path outside repo"),
    (
        "docs/manual-qa.md",
        "pasted into the macOS Packaged App field table",
    ),
    ("website/README.md", "docs/release-blockers.md"),
    ("apps/desktop/src-tauri/tauri.conf.json", "!\"updater\""),
];
