use super::Entry;

pub(super) const ENTRIES: &[Entry] = &[
    ("docs/qa-evidence.md", "docs/release-blockers.md"),
    (
        "docs/qa-evidence.md",
        "license, refund, support contact copy",
    ),
    ("docs/qa-evidence.md", ".codex`/Nix local ignore policy"),
    ("docs/qa-evidence.md", "file names"),
    ("docs/qa-evidence.md", "benchmark CSV path evidence"),
    ("docs/qa-evidence.md", "UDIF `.dmg` artifacts"),
    ("docs/qa-evidence.md", "concrete identity fields"),
    ("docs/qa-evidence.md", "same `.dmg` file evidence"),
    ("docs/qa-evidence.md", "Gatekeeper no-warning evidence"),
    (
        "docs/qa-evidence.md",
        "repository-local and relative app-state/state/output/markdown-output path rejection",
    ),
    ("docs/qa-evidence.md", "`.md` markdown-output rejection"),
    (
        "docs/qa-evidence.md",
        "existing markdown-output no-clobber rejection",
    ),
    ("docs/qa-evidence.md", "--restore-state"),
    ("docs/qa-evidence.md", "Tauri DMG output is normalized"),
    ("docs/qa-evidence.md", "cargo test -p xtask normalize_dmg"),
    ("docs/qa-evidence.md", "non-DMG targets are rejected"),
    (
        "docs/qa-evidence.md",
        "canonical `DropSquash.dmg` file name",
    ),
    ("docs/qa-evidence.md", "wrong-name targets are rejected"),
    (
        "docs/qa-evidence.md",
        "artifact file name instead of local parent directories",
    ),
    ("docs/qa-evidence.md", "publish-check"),
    (
        "docs/qa-evidence.md",
        "release blocker URLs matching the release notes URLs",
    ),
    (
        "docs/qa-evidence.md",
        "public publish references that point to the release notes URLs",
    ),
    (
        "docs/qa-evidence.md",
        "complete manual QA evidence for the public `DropSquash.dmg`",
    ),
    ("docs/qa-evidence.md", "`App build` matching current `HEAD`"),
    (
        "docs/qa-evidence.md",
        "release notes `SHA-256` matching the manual QA `App artifact`",
    ),
    ("docs/qa-evidence.md", "concrete Completion evidence"),
    ("docs/qa-evidence.md", "traceable Evidence reference"),
    ("docs/qa-evidence.md", "release-notes-check"),
    ("docs/qa-evidence.md", "release-notes-prepare"),
    ("docs/qa-evidence.md", "GitHub Release URL"),
    ("docs/qa-evidence.md", "SHA256SUMS line"),
    ("docs/qa-evidence.md", "pending checksum upload placeholder"),
    (
        "docs/qa-evidence.md",
        "stale artifacts older than `HEAD` are rejected",
    ),
    ("docs/qa-evidence.md", "matching Homebrew cask command"),
    ("docs/qa-evidence.md", "Homebrew tap PR evidence draft"),
    (
        "docs/qa-evidence.md",
        "new absolute `.md` path outside the repository",
    ),
    ("docs/qa-evidence.md", "version-matched public Artifact URL"),
    (
        "docs/qa-evidence.md",
        "checksum evidence without the Artifact URL",
    ),
    (
        "docs/qa-evidence.md",
        "conversion/queue/Trash/license action-state evidence",
    ),
    (
        "docs/qa-evidence.md",
        "post-encode postprocess/history guard",
    ),
    (
        "docs/qa-evidence.md",
        "Verified manual QA blockers reject weak evidence",
    ),
    ("docs/qa-evidence.md", "privacy receipt file-name handling"),
    ("docs/qa-evidence.md", "no-success trial/history"),
    ("docs/qa-evidence.md", "unchanged trial counts"),
    ("docs/qa-evidence.md", "UDIF trailer"),
    ("docs/qa-evidence.md", "wrong DMG names"),
    ("docs/qa-evidence.md", "non-canonical homepages"),
    ("docs/qa-evidence.md", "Public website deployment"),
    ("docs/qa-evidence.md", "Live checkout link"),
    ("docs/qa-evidence.md", "pre-release CTA copy"),
    ("docs/qa-evidence.md", "Published checksum"),
    ("docs/qa-evidence.md", "Homebrew cask install"),
    (
        "docs/qa-evidence.md",
        "short, medium, and large local recordings with smaller outputs",
    ),
    ("docs/qa-evidence.md", "versioned `DropSquash.dmg` artifact"),
    ("docs/qa-evidence.md", "matching SHA-256"),
    ("docs/qa-evidence.md", "`auto_updates false`"),
    ("docs/qa-evidence.md", "declares no in-app auto-update"),
    ("docs/qa-evidence.md", "malformed App Store Connect key ids"),
    ("docs/qa-evidence.md", "malformed issuer UUIDs"),
    (
        "docs/qa-evidence.md",
        "missing/empty/placeholder `.p8` files",
    ),
];
