use super::Groups;

pub(super) fn for_label(label: &str) -> Option<Groups> {
    match label {
        "Lemon Squeezy product setup" => Some(&[
            &["sandbox"],
            &["dropsquash"],
            &["intended product"],
            &["license keys enabled"],
            &[
                "private store ids absent",
                "private store ids not recorded",
                "without private store ids",
            ],
        ]),
        "Lemon Squeezy sandbox purchase" => Some(&[
            &["sandbox"],
            &["checkout"],
            &["intended product"],
            &["test buyer"],
            &["order"],
        ]),
        "Valid sandbox activation" => Some(&[
            &["lemon squeezy"],
            &["sandbox"],
            &["activating"],
            &["disabled"],
            &["submit"],
            &["pro"],
            &["fingerprint"],
            &["instance"],
            &["raw key"],
            &["absent", "no raw key", "without raw key"],
            &["cache"],
            &["checked", "inspected", "confirmed"],
        ]),
        "Empty key activation" => Some(&[
            &["activate"],
            &["disabled"],
            &["raw key"],
            &["absent", "no raw key", "without raw key"],
            &[
                "no fingerprint",
                "fingerprint absent",
                "without fingerprint",
            ],
            &["no instance", "instance absent", "without instance"],
            &["cache"],
            &["checked", "inspected", "confirmed"],
        ]),
        "Invalid license key handling" => Some(&[
            &["activating"],
            &["disabled"],
            &["submit"],
            &["friendly"],
            &["raw key"],
            &["absent", "no raw key", "without raw key"],
            &[
                "no fingerprint",
                "fingerprint absent",
                "without fingerprint",
            ],
            &["no instance", "instance absent", "without instance"],
            &["cache"],
            &["checked", "inspected", "confirmed"],
        ]),
        "License network failure" => Some(&[
            &["friendly"],
            &["network"],
            &["existing"],
            &["valid"],
            &["preserved", "intact"],
            &["fingerprint"],
            &["instance"],
            &["raw key"],
            &["absent", "no raw key", "without raw key"],
            &["cache"],
            &["checked", "inspected", "confirmed"],
        ]),
        "Expired license refresh" => Some(&[
            &["attempted", "attempt"],
            &["expired"],
            &["offline grace"],
            &["reconnect"],
            &["blocked"],
            &["before starting"],
            &["raw key"],
            &["absent", "no raw key", "without raw key"],
            &["cache"],
            &["checked", "inspected", "confirmed"],
        ]),
        "Local license forget" => Some(&[
            &["forgetting"],
            &["disabled"],
            &["cache"],
            &["removed", "cleared", "deleted", "clears"],
            &["confirmed"],
            &["observed", "returned"],
            &["trial", "locked"],
        ]),
        _ => None,
    }
}
