use super::Entry;

pub(super) const ENTRIES: &[Entry] = &[
    ("Packaged macOS manual QA", "Tested"),
    ("Packaged macOS manual QA", "public"),
    ("Packaged macOS manual QA", "DropSquash.dmg"),
    ("Packaged macOS manual QA", "Artifact URL"),
    ("Packaged macOS manual QA", "manual-qa-check"),
    ("Empty key activation", "Activate stays disabled"),
    (
        "Empty key activation",
        "raw key, fingerprint, and instance are absent",
    ),
    ("Empty key activation", "local cache was checked"),
    ("Empty key activation", "local cache"),
    (
        "Valid sandbox activation",
        "Activating state disables submit",
    ),
    ("Valid sandbox activation", "Lemon Squeezy"),
    ("Valid sandbox activation", "sandbox"),
    ("Valid sandbox activation", "Pro state"),
    (
        "Valid sandbox activation",
        "64-character lowercase hex fingerprint",
    ),
    ("Valid sandbox activation", "local cache was checked"),
    ("Valid sandbox activation", "`instance_id` fields"),
    ("Valid sandbox activation", "raw key is absent"),
    ("Valid sandbox activation", "local cache"),
    (
        "Invalid license key handling",
        "Activating state disables submit",
    ),
    ("Invalid license key handling", "friendly error"),
    (
        "Invalid license key handling",
        "raw key, fingerprint, and instance are absent",
    ),
    ("Invalid license key handling", "local cache was checked"),
    ("Invalid license key handling", "local cache"),
    ("License network failure", "Friendly network error"),
    (
        "License network failure",
        "existing valid local cache was checked",
    ),
    (
        "License network failure",
        "64-character lowercase hex fingerprint",
    ),
    ("License network failure", "`instance_id` fields"),
    ("License network failure", "raw key is absent"),
    ("License network failure", "local cache"),
    ("Expired license refresh", "expired offline grace cache"),
    ("Expired license refresh", "attempted conversion"),
    ("Expired license refresh", "reconnect prompt"),
    ("Expired license refresh", "conversion is blocked"),
    ("Expired license refresh", "before starting"),
    ("Expired license refresh", "raw key is absent"),
    ("Expired license refresh", "local cache was checked"),
    ("Expired license refresh", "local cache"),
    ("Local license forget", "Forgetting state disables action"),
    ("Local license forget", "confirmed"),
    ("Local license forget", "local cache"),
    ("Local license forget", "removed"),
    ("Local license forget", "observed"),
    ("Local license forget", "trial or locked"),
    ("Benchmark release set", "Release-set benchmark"),
    ("Benchmark release set", "CSV"),
    ("Benchmark release set", "absolute"),
    ("Benchmark release set", "path"),
    ("Benchmark release set", "outside repo"),
    ("Benchmark release set", "backend"),
    ("Benchmark release set", "saved percent"),
    ("Benchmark release set", "duration"),
    ("Benchmark release set", "speed ratio"),
    ("Benchmark release set", "short, medium, and large"),
    ("Benchmark release set", "smaller outputs"),
    ("Benchmark release set", "machine/OS context"),
    ("Benchmark release set", "20% regression threshold"),
    ("Benchmark release set", "release candidate baseline"),
];
