pub(super) const ALL: &[(&str, &str)] = &[
    ("Choose recording conversion", "Choose recording conversion"),
    ("Drag-and-drop conversion", "Drag-and-drop conversion"),
    ("Privacy receipt sidecar", "Privacy receipt sidecar"),
    ("Privacy receipt Finder reveal", "Reveal privacy receipt"),
    ("Duplicate output naming", "Duplicate output naming"),
    ("Finder reveal", "Reveal output"),
    ("Ask source policy", "Ask source policy"),
    ("Trash source policy", "Trash source policy"),
    ("Failed conversion", "Failed conversion"),
    ("Larger output", "Larger output"),
    ("Large-recording cancellation", "Cancellation"),
    ("Benchmark sample set", "Benchmark sample set"),
    (
        "Benchmark regression threshold",
        "Benchmark regression threshold",
    ),
    ("Multi-file queue", "Multi-file queue"),
    ("Queued job cancellation", "Queued job cancellation"),
    ("Batch summary", "Batch summary"),
    ("Lemon Squeezy product setup", "Sandbox product setup"),
    ("Lemon Squeezy sandbox purchase", "Sandbox purchase"),
    ("Valid sandbox activation", "Valid sandbox activation"),
    ("Empty key activation", "Empty key activation"),
    ("Invalid license key handling", "Invalid key activation"),
    ("License network failure", "License network failure"),
    ("Local license forget", "Forget license on this Mac"),
    ("Signed DMG verification", "Codesign verification"),
    (
        "Notarized/stapled DMG verification",
        "Notarization staple verification",
    ),
    ("Signed/notarized Gatekeeper open", "Gatekeeper open test"),
];
