pub(super) const ALL: &[&str] = &[
    "Packaged macOS manual QA",
    "Lemon Squeezy product setup",
    "Lemon Squeezy sandbox purchase",
    "Valid sandbox activation",
    "Invalid license key handling",
    "Local license forget",
    "Public website deployment",
    "Refund policy finalized",
    "Live checkout link",
    "Signed DMG",
    "Notarized and stapled DMG",
    "Gatekeeper clean-machine open",
    "Benchmark release set",
    "Published checksum",
    "Homebrew cask install",
];
