pub(crate) fn run(command: Option<&str>, args: Vec<String>) -> Result<(), String> {
    match command {
        Some("artifact-check") => crate::artifact_check::run(args),
        Some("benchmark") => crate::benchmark::run(args),
        Some("benchmark-csv-check") => crate::benchmark_csv_check::run(args),
        Some("build-week-local-submit-check") => crate::build_week_local_submit_check::run(args),
        Some("build-week-phase5-check") => crate::build_week_phase5_check::run(args),
        Some("build-week-submit-package") => crate::build_week_submit_package::run(args),
        Some("checksum") => crate::checksum::run(args),
        Some("file-size-check") => crate::file_size_check::run(args),
        Some("github-release-plan") => crate::github_release_plan::run(args),
        Some("homebrew-cask") => crate::homebrew_cask::run(args),
        Some("homebrew-cask-check") => crate::homebrew_cask_check::run(args),
        Some("macos-codesign-verify-plan") => crate::macos_codesign_verify_plan::run(args),
        Some("macos-codesign-plan") => crate::macos_codesign_plan::run(args),
        Some("macos-keychain-cleanup-plan") => crate::macos_keychain_cleanup_plan::run(args),
        Some("macos-keychain-plan") => crate::macos_keychain_plan::run(args),
        Some("macos-notary-plan") => crate::macos_notary_plan::run(args),
        Some("macos-signing-plan") => crate::macos_signing_plan::run(args),
        Some("macos-signing-check") => crate::macos_signing_check::run(),
        Some("macos-spctl-plan") => crate::macos_spctl_plan::run(args),
        Some("macos-stapler-plan") => crate::macos_stapler_plan::run(args),
        Some("manual-qa-clean-draft") => crate::manual_qa_clean_draft::run(args),
        Some("manual-qa-bad-input") => crate::manual_qa_bad_input::run(args),
        Some("manual-qa-drag-drop") => crate::manual_qa_drag_drop::run(args),
        Some("manual-qa-drag-report") => crate::manual_qa_drag_report::run(args),
        Some("manual-qa-distribution-rerun") => crate::manual_qa_distribution_rerun::run(args),
        Some("manual-qa-forget-license") => crate::manual_qa_forget_license::run(args),
        Some("manual-qa-fill-benchmark") => crate::manual_qa_benchmark_fill::run(args),
        Some("manual-qa-fill-benchmark-threshold") => {
            crate::manual_qa_fill_benchmark_threshold::run(args)
        }
        Some("manual-qa-fill-check") => crate::manual_qa_fill_check::run(args),
        Some("manual-qa-fill-local-proof") => crate::manual_qa_fill_local_proof::run(args),
        Some("manual-qa-check") => crate::manual_qa_check::run(args),
        Some("manual-qa-installed-app") => crate::manual_qa_installed_app::run(args),
        Some("manual-qa-license-rerun") => crate::manual_qa_license_rerun::run(args),
        Some("manual-qa-license-cache") => crate::manual_qa_license_cache::run(args),
        Some("manual-qa-launch-app") => crate::manual_qa_launch_app::run(args),
        Some("manual-qa-link-samples") => crate::manual_qa_link_samples::run(args),
        Some("manual-qa-merge-prepared") => crate::manual_qa_merge_prepared::run(args),
        Some("manual-qa-open-chooser") => crate::manual_qa_open_chooser::run(args),
        Some("manual-qa-packaged-rerun") => crate::manual_qa_packaged_rerun::run(args),
        Some("manual-qa-paid-beta-rerun") => crate::manual_qa_paid_beta_rerun::run(args),
        Some("manual-qa-pending") => crate::manual_qa_pending::run(args),
        Some("manual-qa-p1-review") => crate::manual_qa_p1_review::run(args),
        Some("manual-qa-fill-release-gates") => crate::manual_qa_release_gate_fill::run(args),
        Some("manual-qa-prepare") => crate::manual_qa_prepare::run(args),
        Some("manual-qa-ready-all") => crate::manual_qa_ready_all::run(args),
        Some("manual-qa-ready-distribution") => crate::manual_qa_ready_distribution::run(args),
        Some("manual-qa-ready-license") => crate::manual_qa_ready_license::run(args),
        Some("manual-qa-ready-local-proof") => crate::manual_qa_ready_local_proof::run(args),
        Some("manual-qa-secure-share-observe") => crate::manual_qa_secure_share_observe::run(args),
        Some("manual-qa-secure-share-report") => crate::manual_qa_secure_share_report::run(args),
        Some("manual-qa-seed-license-cache") => crate::manual_qa_seed_license_cache::run(args),
        Some("manual-qa-window-capture") => crate::manual_qa_window_capture::run(args),
        Some("manual-qa-window-probe") => crate::manual_qa_window_probe::run(args),
        Some("media-policy-check") => crate::media_policy_check::run(),
        Some("normalize-dmg") => crate::normalize_dmg::run(args),
        Some("paid-beta-check") => crate::paid_beta_check::run(args),
        Some("phase5-doc-honesty-check") => crate::phase5_doc_honesty_check::run(args),
        Some("privacy-policy-check") => crate::privacy_policy_check::run(),
        Some("productization-status") => crate::productization_status::run(args),
        Some("public-web-probe") => crate::public_web_probe::run(args),
        Some("public-web-ready") => crate::public_web_ready::run(args),
        Some("public-web-rerun") => crate::public_web_rerun::run(args),
        Some("publish-check") => crate::publish_check::run(args),
        Some("release-check") => crate::release_check::run(),
        Some("release-notes-check") => crate::release_notes_check::run(args),
        Some("release-notes-prepare") => crate::release_notes_prepare::run(args),
        Some("secure-share-evidence-check") => crate::secure_share_evidence_check::run(args),
        Some("signed-dmg-check") => crate::signed_dmg_check::run(args),
        Some("signed-dmg-copy") => crate::signed_dmg_copy::run(args),
        Some("signed-dmg-prepare") => crate::signed_dmg_prepare::run(args),
        Some("website-check") => crate::website_check::run(args),
        _ => usage(),
    }
}

fn usage() -> Result<(), String> {
    eprintln!("usage: cargo run -p xtask -- <artifact-check|benchmark|benchmark-csv-check|build-week-local-submit-check|build-week-phase5-check|build-week-submit-package|checksum|file-size-check|github-release-plan|homebrew-cask|homebrew-cask-check|macos-codesign-plan|macos-codesign-verify-plan|macos-keychain-cleanup-plan|macos-keychain-plan|macos-notary-plan|macos-signing-check|macos-signing-plan|macos-spctl-plan|macos-stapler-plan|manual-qa-bad-input|manual-qa-check|manual-qa-clean-draft|manual-qa-distribution-rerun|manual-qa-drag-drop|manual-qa-drag-report|manual-qa-fill-benchmark|manual-qa-fill-benchmark-threshold|manual-qa-fill-check|manual-qa-fill-local-proof|manual-qa-fill-release-gates|manual-qa-forget-license|manual-qa-installed-app|manual-qa-launch-app|manual-qa-license-cache|manual-qa-license-rerun|manual-qa-link-samples|manual-qa-merge-prepared|manual-qa-open-chooser|manual-qa-packaged-rerun|manual-qa-paid-beta-rerun|manual-qa-p1-review|manual-qa-pending|manual-qa-prepare|manual-qa-ready-all|manual-qa-ready-distribution|manual-qa-ready-license|manual-qa-ready-local-proof|manual-qa-secure-share-report|manual-qa-seed-license-cache|manual-qa-window-capture|manual-qa-window-probe|media-policy-check|normalize-dmg|paid-beta-check|phase5-doc-honesty-check|privacy-policy-check|productization-status|public-web-probe|public-web-ready|public-web-rerun|publish-check|release-check|release-notes-check|release-notes-prepare|secure-share-evidence-check|signed-dmg-check|signed-dmg-copy|signed-dmg-prepare|website-check> [files...]");
    std::process::exit(2);
}
