mod artifact_age;
mod artifact_check;
mod benchmark;
mod benchmark_csv_check;
mod build_week_local_submit_check;
mod build_week_phase5_check;
mod build_week_submit_package;
mod checksum;
mod csv_evidence;
mod current_date;
mod dispatch;
mod dmg;
mod dmg_cleanup_claims;
mod file_size_check;
mod git_head_match;
mod git_status;
mod github_release_plan;
mod homebrew_cask;
mod homebrew_cask_check;
mod macos_codesign_plan;
mod macos_codesign_verify_plan;
mod macos_keychain_cleanup_plan;
mod macos_keychain_plan;
mod macos_notary_plan;
mod macos_signing_check;
mod macos_signing_plan;
mod macos_spctl_plan;
mod macos_stapler_plan;
mod manual_qa_bad_input;
mod manual_qa_benchmark_fill;
mod manual_qa_check;
mod manual_qa_clean_draft;
mod manual_qa_dirty_worktree;
mod manual_qa_distribution_rerun;
mod manual_qa_drag_drop;
mod manual_qa_drag_report;
mod manual_qa_fill_benchmark_threshold;
mod manual_qa_fill_check;
mod manual_qa_fill_local_proof;
mod manual_qa_forget_license;
mod manual_qa_installed_app;
mod manual_qa_launch_app;
mod manual_qa_license_cache;
mod manual_qa_license_rerun;
mod manual_qa_link_samples;
mod manual_qa_merge_prepared;
mod manual_qa_observation;
mod manual_qa_open_chooser;
mod manual_qa_p1_review;
mod manual_qa_packaged_rerun;
mod manual_qa_paid_beta_rerun;
mod manual_qa_pending;
mod manual_qa_prepare;
mod manual_qa_ready_all;
mod manual_qa_ready_distribution;
mod manual_qa_ready_license;
mod manual_qa_ready_local_proof;
mod manual_qa_release_gate_fill;
mod manual_qa_secure_share_observe;
mod manual_qa_secure_share_report;
mod manual_qa_seed_license_cache;
mod manual_qa_window_capture;
mod manual_qa_window_probe;
mod media_policy_check;
mod normalize_dmg;
mod paid_beta_check;
mod phase5_doc_honesty_check;
mod privacy_policy_check;
mod productization_status;
mod public_url;
mod public_web_probe;
mod public_web_ready;
mod public_web_rerun;
mod publish_check;
mod release_check;
mod release_notes_check;
mod release_notes_prepare;
mod release_url_fields;
mod secret_text;
mod secure_share_evidence_check;
mod signed_dmg_check;
mod signed_dmg_copy;
mod signed_dmg_prepare;
mod url_origin;
mod url_scheme;
mod website_check;

fn main() {
    let mut args = std::env::args().skip(1);
    let result = dispatch::run(args.next().as_deref(), args.collect());
    if let Err(error) = result {
        eprintln!("{error}");
        std::process::exit(1);
    }
}
