pub(super) const TEXT: &[(&str, &str)] = &[
    ("index.html", "Release status"),
    (
        "index.html",
        "DropSquash is the automatic local post-processor for Mac screen recordings.",
    ),
    (
        "index.html",
        "include built-in screen recording or automatic privacy masking in the current beta",
    ),
    ("release-status/index.html", "Paid beta is not public yet"),
    ("release-status/index.html", "Developer ID"),
    ("release-status/index.html", "signed and notarized"),
    ("release-status/index.html", "docs/release-blockers.md"),
    ("release-status/index.html", "Evidence reference"),
    (
        "release-status/index.html",
        "Lemon Squeezy sandbox validation",
    ),
    (
        "release-status/index.html",
        "automatic local post-processor for Mac screen recordings",
    ),
    (
        "release-status/index.html",
        "future candidates, not current release promises",
    ),
    ("release-status/index.html", "../download.html"),
    ("release-status/index.html", "../pricing.html"),
    ("release-status/index.html", "../privacy.html"),
    ("release-status/index.html", "../terms.html"),
    ("release-status/index.html", "../license.html"),
    ("release-status/index.html", "../support.html"),
    ("release-status/index.html", "../refund.html"),
    ("download.html", "macOS beta"),
    ("download.html", "Developer ID signing"),
    ("download.html", "DropSquash.dmg"),
    ("download.html", "notarization"),
    ("download.html", "checksum"),
    ("download.html", "release-status/"),
    ("pricing.html", "Checkout opens after"),
    ("pricing.html", "Developer ID signing"),
    ("pricing.html", "notarization"),
    ("pricing.html", "Lemon Squeezy sandbox validation"),
    ("pricing.html", "No checkout link is live yet"),
    ("pricing.html", "release-status/"),
    ("pricing.html", "Beta price is draft"),
    ("pricing.html", "20 successful smaller conversions are free"),
    ("pricing.html", "Your recordings stay local"),
    ("pricing.html", "refund.html"),
    ("pricing.html", "not as a recorder or timeline editor"),
    (
        "pricing.html",
        "does not include built-in recording or automatic privacy masking in Pro",
    ),
    (
        "pricing.html",
        "Failed, cancelled, or larger-result conversions do not count",
    ),
    ("pricing.html", "License policy"),
    ("terms.html", "draft terms"),
    ("terms.html", "local-first macOS app"),
    ("terms.html", "License policy"),
    ("terms.html", "Support"),
    ("terms.html", "Refund Policy"),
    ("terms.html", "paid beta"),
    ("privacy.html", "does not upload media"),
    ("privacy.html", "Telemetry is off by default"),
    ("privacy.html", "privacy receipts"),
    ("privacy.html", "uploaded_bytes = 0"),
    ("privacy.html", "metadata_policy = preserve"),
    ("privacy.html", "file names instead of absolute paths"),
    ("privacy.html", "License activation contacts Lemon Squeezy"),
    ("privacy.html", "updater is disabled"),
    ("license.html", "license-key fingerprint"),
    ("license.html", "Your recordings stay local"),
    ("license.html", "does not persist the raw license key"),
    ("license.html", "local license cache"),
    ("license.html", "Offline grace"),
    ("license.html", "refresh Pro on that Mac"),
    ("license.html", "Server-side deactivation"),
    ("license.html", "not automatic"),
    ("license.html", "support.html"),
    ("license.html", "refund.html"),
    ("support.html", "Do not send screen recordings"),
    ("support.html", "FAQ"),
    ("support.html", "What is a privacy receipt?"),
    ("support.html", "metadata_policy = preserve"),
    ("support.html", "Does DropSquash upload my videos?"),
    ("support.html", "does not upload media"),
    ("support.html", "Does it use command-line media tools?"),
    ("support.html", "does not shell out"),
    ("support.html", "command-line media tools"),
    ("support.html", "app version"),
    ("support.html", "GitHub Issues"),
    ("support.html", "paid beta support address"),
    ("refund.html", "draft policy"),
    ("refund.html", "checkout goes live"),
    ("refund.html", "cannot activate"),
    ("refund.html", "basic local conversion workflow"),
    ("refund.html", "support.html"),
    ("refund.html", "order email"),
    ("refund.html", "Lemon Squeezy order flow"),
];
