pub(super) const TEXT: &[(&str, &str)] = &[
    ("index.html", "Release status"),
    ("release-status/index.html", "Paid beta is not public yet"),
    ("release-status/index.html", "signed and notarized"),
    ("release-status/index.html", "docs/release-blockers.md"),
    ("release-status/index.html", "Evidence reference"),
    ("download.html", "macOS beta"),
    ("download.html", "DropSquash.dmg"),
    ("download.html", "notarization"),
    ("download.html", "checksum"),
    ("download.html", "release-status/"),
    ("pricing.html", "Checkout opens after"),
    ("pricing.html", "signed beta release"),
    ("pricing.html", "release-status/"),
    ("pricing.html", "10 successful conversions are free"),
    (
        "pricing.html",
        "Failed or cancelled conversions do not count",
    ),
    ("pricing.html", "License policy"),
    ("privacy.html", "does not upload media"),
    ("privacy.html", "Telemetry is off by default"),
    ("privacy.html", "privacy receipts"),
    ("privacy.html", "uploaded_bytes = 0"),
    ("privacy.html", "metadata_policy = preserve"),
    ("privacy.html", "file names instead of absolute paths"),
    ("privacy.html", "License activation contacts Lemon Squeezy"),
    ("license.html", "license-key fingerprint"),
    ("license.html", "does not persist the raw license key"),
    ("license.html", "local license cache"),
    ("license.html", "Offline grace"),
    ("license.html", "Server-side deactivation"),
    ("license.html", "not automatic"),
    ("support.html", "Do not send screen recordings"),
    ("support.html", "FAQ"),
    ("support.html", "What is a privacy receipt?"),
    ("support.html", "metadata_policy = preserve"),
    ("support.html", "Does DropSquash upload my videos?"),
    ("support.html", "Does it use ffmpeg?"),
    ("support.html", "app version"),
    ("support.html", "GitHub Issues"),
    ("support.html", "paid beta support address"),
    ("refund.html", "draft policy"),
    ("refund.html", "checkout goes live"),
    ("refund.html", "cannot activate"),
    ("refund.html", "basic local conversion workflow"),
    ("refund.html", "order email"),
    ("refund.html", "Lemon Squeezy order flow"),
];
