pub(super) const CI: &[&str] = &[
    "permissions:",
    "contents: read",
    "Install Linux desktop dependencies",
    "libwebkit2gtk-4.1-dev",
    "cargo fmt --all -- --check",
    "cargo run -p xtask -- file-size-check",
    "cargo run -p xtask -- website-check",
    "cargo run -p xtask -- release-check",
    "clippy macOS",
    "cargo clippy --workspace --exclude dropsquash-desktop --all-targets -- -D warnings",
    "test macOS",
    "cargo test --workspace --exclude dropsquash-desktop",
    "clippy portable crates",
    "test portable crates",
    "cachix/install-nix-action@v31",
    "nix flake check --no-build --all-systems",
];

pub(super) const RELEASE: &[&str] = &[
    "tags:",
    "\"v*.*.*\"",
    "permissions:",
    "contents: read",
    "environment: production",
    "Install Linux desktop dependencies",
    "libwebkit2gtk-4.1-dev",
    "components: rustfmt, clippy",
    "cargo fmt --all -- --check",
    "cargo clippy --workspace --all-targets -- -D warnings",
    "cargo test --workspace",
    "cargo run -p xtask -- file-size-check",
    "cargo run -p xtask -- website-check",
    "cargo run -p xtask -- manual-qa-check",
    "cargo run -p xtask -- release-check",
    "pnpm/action-setup@v4",
    "version: 10.34.0",
    "actions/setup-node@v4",
    "node-version: 24.16.0",
    "pnpm --dir apps/desktop tauri build --bundles app,dmg --no-sign --ci",
    "cargo run -p xtask -- normalize-dmg target/release/bundle/dmg",
    "cargo run -p xtask -- artifact-check target/release/bundle/dmg/DropSquash.dmg",
    "dropsquash-unsigned-dmg",
    "cargo run -p xtask -- checksum target/release/bundle/dmg/DropSquash.dmg --output SHA256SUMS",
    "actions/upload-artifact@v4",
    "dropsquash-unsigned-dmg-checksum",
    "Prepare App Store Connect key file",
    "APPLE_API_KEY_P8: ${{ secrets.APPLE_API_KEY_P8 }}",
    "install -m 600 /dev/null \"$key_path\"",
    "APPLE_API_KEY_PATH=$key_path",
    "APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}",
    "APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}",
    "APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}",
    "APPLE_CODESIGN_IDENTITY: ${{ vars.APPLE_CODESIGN_IDENTITY }}",
    "cargo run -p xtask -- macos-signing-check",
    "cargo run -p xtask -- macos-signing-plan target/release/bundle/dmg/DropSquash.dmg \"$RUNNER_TEMP/dropsquash-signed\"",
    "cargo run -p xtask -- macos-keychain-plan \"$RUNNER_TEMP/dropsquash-signing\"",
    "Import macOS signing certificate",
    "security list-keychains -d user -s \"$keychain\"",
    "cargo run -p xtask -- signed-dmg-prepare target/release/bundle/dmg/DropSquash.dmg \"$RUNNER_TEMP/dropsquash-signed\"",
    "cargo run -p xtask -- signed-dmg-copy target/release/bundle/dmg/DropSquash.dmg \"$RUNNER_TEMP/dropsquash-signed\"",
    "cargo run -p xtask -- macos-codesign-plan \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\" \"Developer ID Application: ...\"",
    "codesign --force --options runtime --timestamp --sign \"$APPLE_CODESIGN_IDENTITY\"",
    "cargo run -p xtask -- macos-codesign-verify-plan \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\"",
    "codesign --verify --deep --strict --verbose=4 \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\"",
    "codesign -dv --verbose=4 \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\"",
    "cargo run -p xtask -- macos-notary-plan \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\" --api-key",
    "Notarize macOS DMG",
    "xcrun notarytool submit \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\" --wait --key \"$APPLE_API_KEY_PATH\" --key-id \"$APPLE_API_KEY\" --issuer \"$APPLE_API_ISSUER\"",
    "cargo run -p xtask -- macos-stapler-plan \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\"",
    "Staple macOS DMG",
    "xcrun stapler staple \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\"",
    "xcrun stapler validate \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\"",
    "cargo run -p xtask -- macos-spctl-plan \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\"",
    "Assess macOS Gatekeeper",
    "spctl --assess --type open --verbose=4 \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\"",
    "Check signed DMG artifact",
    "cargo run -p xtask -- signed-dmg-check \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\" target/release/bundle/dmg/DropSquash.dmg",
    "Write signed DMG checksum",
    "cargo run -p xtask -- checksum \"$RUNNER_TEMP/dropsquash-signed/DropSquash.dmg\" --output \"$RUNNER_TEMP/dropsquash-signed/SHA256SUMS\"",
    "Upload signed DMG artifact",
    "dropsquash-signed-dmg",
    "${{ runner.temp }}/dropsquash-signed/DropSquash.dmg",
    "Upload signed DMG checksum",
    "dropsquash-signed-dmg-checksum",
    "${{ runner.temp }}/dropsquash-signed/SHA256SUMS",
    "cargo run -p xtask -- macos-keychain-cleanup-plan \"$RUNNER_TEMP/dropsquash-signing\"",
    "Cleanup macOS signing keychain",
    "always() && matrix.os == 'macos-latest'",
    "Block unsigned Phase 0 release",
    "Public Phase 0 release is blocked until publish-check evidence is complete.",
    "exit 1",
];

pub(super) const RELEASE_FORBIDDEN: &[&str] = &[
    "APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}",
    "APPLE_API_KEY_PATH: ${{ secrets.APPLE_API_KEY_PATH }}",
];

pub(super) const DESKTOP: &[&str] = &[
    "permissions:",
    "contents: read",
    "pnpm --dir apps/desktop/web install --frozen-lockfile",
    "pnpm --dir apps/desktop/web test",
    "pnpm --dir apps/desktop/web build",
    "dtolnay/rust-toolchain@1.95.0",
    "desktop-rust-macos",
    "cargo test -p dropsquash-desktop",
];

pub(super) const SECURITY: &[&str] = &[
    "permissions:",
    "contents: read",
    "Install Linux desktop dependencies",
    "libwebkit2gtk-4.1-dev",
    "cargo audit",
    "cargo deny check",
    "cargo run -p xtask -- media-policy-check",
    "cargo run -p xtask -- privacy-policy-check",
];
